#pragma once
#include <string_view>
#include <unordered_map>

namespace roomcats {
enum class Language { English, Chinese };
inline Language g_language = Language::English;
inline bool Chinese() { return g_language == Language::Chinese; }
inline bool SetLanguage(Language language) {
    if (g_language == language) return false;
    g_language = language;
    return true;
}

// The game's trait/class text is generated in both languages. These are the
// Mod's own UI strings and operation messages; unknown strings remain visible
// in Chinese until explicitly translated rather than silently changing data.
inline const char* Tx(const char* chinese) {
    if (Chinese()) return chinese;
    static const std::unordered_map<std::string_view, const char*> english = {
        {"猫咪列表###RoomCatsPanel", "Cat List###RoomCatsPanel"},
        {"猫咪列表", "Cat List"},
        {"筛选设置###ScreeningSettings", "Screening Settings###ScreeningSettings"},
        {"返回名单##ReviewBack", "Back to List##ReviewBack"},
        {"返回上一级##ParentBack", "Back##ParentBack"},
        {"位置", "Location"}, {"送至", "Send to"}, {"名字/职业", "Name / Class"},
        {"父母", "Parents"}, {"年龄", "Age"}, {"性/取/繁", "S/O/I"}, {"总", "Total"},
        {"力", "STR"}, {"敏", "DEX"}, {"体", "CON"}, {"智", "INT"},
        {"速", "SPD"}, {"魅", "CHA"}, {"运", "LCK"},
        {"好突变", "Good"}, {"坏突变", "Bad"}, {"疾病", "Disease"},
        {"力量", "Strength"}, {"敏捷", "Dexterity"}, {"体质", "Constitution"},
        {"智力", "Intelligence"}, {"速度", "Speed"}, {"魅力", "Charisma"},
        {"幸运", "Luck"}, {"总计", "Total"}, {"全部突变", "All mutations"},
        {"固定属性合计", "Fixed stat total"}, {"条件效果见左侧", "Details on left"},
        {"处理方式", "Action"}, {"筛选原因", "Screening reason"},
        {"排序", "Sort"}, {"实", "R"}, {"遗", "G"},
        {"年龄在降序和升序之间切换。", "Switch age between descending and ascending."},
        {"点击表头依次切换：真实降序、真实升序、遗传降序、遗传升序。", "Click to cycle: real descending, real ascending, genetic descending, genetic ascending."},
        {"移动中…", "Moving..."}, {"正在移送…", "Moving..."},
        {"选择去向", "Choose"}, {"暂无已解锁角色", "No unlocked NPCs"},
        {"此猫不在家园，无法移动或投送。", "This cat is not at home and cannot be moved or sent."},
        {"%s\n职业：%s\n%s", "%s\nClass: %s\n%s"},
        {"未知", "Unknown"}, {"此猫不在家园，无法打开家园详情。", "This cat is not at home; its house details cannot be opened."},
        {"点击打开猫咪界面", "Click to open cat details"},
        {"%s\n%s\n点击查看父母表格", "%s\n%s\nClick to view the parent list"},
        {"%s\n基线：真实 7 / 遗传 5%s", "%s\nBaseline: real 7 / genetic 5%s"},
        {"（总属性按七项平均）", " (total is averaged over seven stats)"},
        {"无", "None"}, {"详情暂不可用。", "Details are temporarily unavailable."},
        {"老猫数量控制复查", "Adult population review"}, {"新生猫筛选复查", "Newborn screening review"},
        {" 的父母", "'s parents"}, {"  %zu 只猫咪", "  %zu cats"},
        {"此房间暂无猫咪。", "No cats in this room."}, {"家园暂无猫咪。", "No cats at home."},
        {"%zu / 优%d", "%zu / quality %d"},
        {"滚轮上下 · Shift+滚轮左右 · 点击表头排序 · %s", "Wheel: vertical · Shift+wheel: horizontal · Click headers to sort · %s"},
        {"Esc 返回上一级", "Esc: back"}, {"Esc 关闭", "Esc: close"},
        {"手柄：左摇杆移动光标 · A 点击 · B 返回 · 右摇杆滚动", "Controller: left stick moves cursor · A clicks · B goes back · right stick scrolls"},
        {"全屋猫咪", "All cats"}, {"阁楼", "Attic"}, {"一楼左", "1F left"},
        {"一楼右", "1F right"}, {"二楼左", "2F left"},
        {"二楼右", "2F right"}, {"出征区域", "Adventure area"}, {"地下室 ", "Basement "},
        {"箱子", "Box"}, {"箱子 ", "Box "}, {"其他位置", "Other location"},
        {"未分配", "Unassigned"}, {"不在家园", "Not at home"},
        {"资料未找到", "Record not found"}, {"已故", "Deceased"},
        {"未命名猫咪", "Unnamed cat"}, {"未知父母", "Unknown parent"},
        {"房间数据暂时不可用，请稍后重试。", "Room data is temporarily unavailable. Please retry."},
        {"猫咪数据正在变化，请重新打开列表。", "Cat data is changing. Reopen the list."},
        {"部分猫咪的名字未能读取，请稍后重试。", "Some cat names could not be read. Please retry."},
        {"公", "M"}, {"母", "F"}, {"异", "H"}, {"同", "G"}, {"双", "B"},
        {"轻", "L"}, {"中", "M"}, {"重", "H"},
        {"暂无对应效果说明", "No matching effect description"},
        {"新生猫筛选", "Newborn screening"}, {"老猫数量控制", "Adult population control"},
        {"筛选设置", "Screening settings"}, {"确定处理", "Confirm actions"},
        {"语言", "Language"},
        {"停止处理", "Stop processing"}, {"重新复查", "Review again"},
        {"不遗弃（原地保留）", "Keep (leave in place)"}, {"移至 ", "Move to "},
        {"送至 ", "Send to "}, {"送至 NPC ", "Send to NPC "}, {"遗弃", "Discard"},
        {"此NPC当前不可用", "This NPC is currently unavailable"},
        {"已保留原选择：%s。请等待或手动修改去向。", "Original selection kept: %s. Wait or change the destination manually."},
        {"无可遗弃。本轮处理进度见下方。", "No cats to discard. Processing progress is below."},
        {"无可遗弃，存在调房：%d 只猫咪。", "No cats to discard; %d cats have room moves."},
        {"请点击右上角“确定处理”后执行调房。悬停下方“调房”数量可查看名单。", "Click Confirm actions in the upper right to move them. Hover over the move count below for the list."},
        {"无可遗弃，无需调房；有 %d 只猫咪需要打标，点击“确定处理”后执行。", "No cats to discard or move; %d cats need a mark. Click Confirm actions to apply it."},
        {"无可遗弃，也无需调房或打标。", "No cats to discard, move or mark."},
        {"打标 %d · 调房 %d · NPC %d · 遗弃 %d · 原地保留 %d", "Mark %d · Move %d · NPC %d · Discard %d · Keep %d"},
        {"%s：%s → %s（遗传 %lld，优质变异 %d）", "%s: %s → %s (genetic %lld, quality mutations %d)"},
        {"预计总数 %d → %d / %d · 房子保护 %d · 舒适度：顶楼 %.0f / 二楼左 %.0f / 二楼右 %.0f / 一楼左 %.0f", "Projected total %d → %d / %d · House-protected %d · Comfort: attic %.0f / second left %.0f / second right %.0f / first left %.0f"},
        {"保留限制或手动选择使目标未达成。目标舒适度：%d / %d / %d / %d。", "Protected cats or manual choices prevent the target. Comfort targets: %d / %d / %d / %d."},
        {"年龄>1 · 遗传门槛 %d/%d/%d · 战备真实下限 %d · 房子标记保留", "Age >1 · Genetic thresholds %d/%d/%d · Combat real minimum %d · House marks protected"},
        {"遗传门槛 %d/%d/%d · 新生名额 %d/%d · 战备真实下限 %d · 房子标记保留", "Genetic thresholds %d/%d/%d · Newborn slots %d/%d · Combat real minimum %d · House marks protected"},
        {"%zu / %zu 步：%s", "Step %zu / %zu: %s"},
        {"确认前不修改猫咪。悬停上方数量可查看调房摘要。", "Cats are unchanged until confirmation. Hover over the counts above for planned moves."},
        {"新生猫", "Newborn cats"}, {"老猫", "Adult cats"},
        {"恢复默认", "Restore defaults"}, {"保存并关闭", "Save and close"}, {"取消", "Cancel"},
        {"可填范围：%d 至 %d", "Allowed range: %d to %d"},
        {"排序：属性 > 优质变异 > 有无职业。房子标记始终保护；小猫年龄=1，老猫年龄>1。", "Ranking: stats > quality mutations > class. House-marked cats are protected; newborn age = 1, adults age > 1."},
        {"修改只影响新生成的方案；保存后仍须复查并确认。数值可直接输入，也可点击加减按钮。", "Changes affect newly generated plans. Review and confirm again. Enter values directly or use the +/- buttons."},
        {"二楼新生每房最多可设6只；对面出生数量需小于等于每房上限。", "The second-floor newborn limit is at most 6 per room; the cross-room target cannot exceed it."},
        {"筛选设置无效，已恢复默认值：", "Invalid screening settings; restored defaults: "},
        {"筛选设置已保存；下次生成方案使用新规则", "Screening settings saved; the next plan will use the new rules"},
        {"筛选设置已保存", "Screening settings saved"},
        {"请先等待当前操作完成", "Wait for the current action to finish"},
        {"当前状态已处理，无需重复执行", "This state has already been processed"},
        {"已恢复 ", "Restored "}, {" 只猫的处理去向，请复查后确认", " cats' choices; review and confirm"},
        {"默认优先送至第一个可选NPC；请复查后确认", "Defaults to the first available NPC; review and confirm"},
        {"老猫控制 ", "Adult control "}, {"新生筛选 ", "Newborn screening "}, {" 步：", " steps: "},
        {"顶楼遗传下限", "Attic genetic minimum"}, {"二楼遗传下限", "Second-floor genetic minimum"},
        {"一楼左遗传下限", "First-floor left genetic minimum"},
        {"顶楼优先目标敏捷", "Prioritize attic target DEX"},
        {"顶楼目标遗传敏捷", "Attic target genetic DEX"},
        {"坏变异转战备筛选", "Send bad mutations to combat screening"},
        {"疾病转战备筛选", "Send diseases to combat screening"},
        {"战备真实总和下限", "Combat real-stat minimum"},
        {"启用偏科淘汰", "Reject uneven combat stats"},
        {"低属性判定值（小于等于）", "Low-stat cutoff (at or below)"},
        {"低属性达到几项则淘汰", "Number of low stats to reject"},
        {"顶楼新生保留上限", "Attic newborn limit"},
        {"二楼每房新生保留上限", "Second-floor newborn limit per room"},
        {"二楼每房期望对面出生数量", "Second-floor cross-room birth target"},
        {"允许新生猫晋升", "Allow newborn promotion"},
        {"每个原始楼层晋升上限", "Promotion limit per source floor"},
        {"拆分近亲小猫的父母", "Separate inbred kittens' parents"},
        {"一楼左较弱亲本也降级", "Demote weaker parent from first-floor left"},
        {"自动添加出生房间标记", "Automatically mark birth room"},
        {"带职业成年亲本不转战备", "Do not send classed adult parents to combat"},
        {"家园总数量上限", "Total house population limit"},
        {"顶楼舒适度下限", "Attic comfort minimum"},
        {"二楼左舒适度下限", "Second-floor left comfort minimum"},
        {"二楼右舒适度下限", "Second-floor right comfort minimum"},
        {"一楼左舒适度下限", "First-floor left comfort minimum"},
        {"一楼左允许轻度近亲", "Allow mild inbreeding on first-floor left"},
        {"带职业老猫不转入战备", "Do not send classed adults to combat"},
        {" 需要在 ", " must be between "}, {" 至 ", " and "}, {" 之间", ""},
        {"遗传门槛需满足：顶楼 ≥ 二楼 ≥ 一楼左", "Genetic minimums must satisfy: attic ≥ second floor ≥ first-floor left"},
        {"对面出生数量不能超过二楼每房保留上限", "Cross-room birth target cannot exceed the second-floor room limit"},
        {"配置项 ", "Setting "}, {" 的数值无效", " has an invalid value"},
        {"家园或舒适度数据尚未就绪，请稍后重新生成老猫方案", "House or comfort data is not ready. Regenerate the adult plan shortly."},
        {"房间或舒适度数据不完整，无法生成老猫方案", "Room or comfort data is incomplete; cannot generate the adult plan."},
        {"需要顶楼、二楼左右、一楼左右五个房间", "The attic and four first/second-floor rooms are required."},
        {"猫咪或房间效果数据不完整，无法生成老猫方案", "Cat or room effect data is incomplete; cannot generate the adult plan."},
        {" 的属性或近亲数据不完整，请刷新后重试", " has incomplete stats or inbreeding data. Refresh and retry."},
        {"有坏变异或疾病，转备战筛选", "Bad mutation or disease; route to combat screening"},
        {"近亲程度超过允许范围，转备战筛选", "Inbreeding exceeds the allowed range; route to combat screening"},
        {"遗传 ", "Genetic "}, {"，按品质与舒适度分配至 ", "; assigned by quality and comfort to "},
        {"带职业老猫未能留在繁育房，不转战备，进入淘汰复查", "Classed adult could not remain in breeding; review for removal without combat transfer"},
        {"备战真实总和低于", "Combat real-stat total below "},
        {"或至少", " or at least "}, {"项真实值≤", " real stats ≤"},
        {"总数控制在", "Keep total at "}, {"只，按所在层级与能力择弱淘汰", " cats; remove weaker cats by tier and ability"},
        {"只调整年龄大于1的猫；房子标记始终保留。幼猫、箱子及其他位置计入总数但不自动调动。", "Only cats older than 1 are moved; house-marked cats are protected. Kittens, boxes and other locations count toward total but are not moved automatically."},
        {"繁育房按遗传属性、优质变异、有无职业比较；战备按真实属性、优质能力、有无职业比较。", "Breeding cats rank by genetics, quality mutations and class; combat cats rank by real stats, quality abilities and class."},
        {"顶楼优先遗传敏捷为", "The attic prioritizes genetic DEX "},
        {"的猫。", " cats."},
        {"繁育房淘汰的带职业老猫不转战备，直接进入淘汰复查；原本在战备房的猫仍按真实能力筛选。", "Classed adults rejected from breeding go directly to removal review; existing combat cats are screened by real ability."},
        {"受保护猫、幼猫或舒适度限制，当前方案无法降至", "Protected cats, kittens or comfort limits prevent reaching "},
        {"只；不会扩大淘汰范围。", " cats; removal scope will not be widened."},
        {" 受固定住猫或家具限制，无法达到舒适度目标。", " cannot meet its comfort target because of fixed residents or furniture."},
        {"家园数据暂不可用，无法生成方案", "House data is unavailable; cannot generate a plan"},
        {"同一层存在多个房间，无法唯一确定去向", "Multiple rooms on one floor prevent a unique destination"},
        {"猫咪 ID 重复，无法生成可靠方案", "Duplicate cat ID prevents a reliable plan"},
        {" 的属性或近亲数据不完整，请刷新后再筛选", " has incomplete stats or inbreeding data. Refresh before screening."},
        {" 的近亲父母记录不完整，无法决定亲本降级", " has an incomplete parent record; cannot choose a parent to demote"},
        {" 的双亲均有房子标记，保留亲本位置", " has two house-marked parents; both remain in place"},
        {"近亲小猫转备战", "Inbred kitten moves to combat"}, {"近亲亲本降一级", "Inbred parent demoted one tier"},
        {" 的父母已不同时在繁育房，无需重复拆分", " has parents no longer together in a breeding room; no second separation needed"},
        {"达到顶楼门槛，参加顶楼筛选", "Meets attic threshold; competes for attic places"},
        {"达到二楼门槛，晋升一级", "Meets second-floor threshold; promoted one tier"},
        {"顶楼遗传低于", "Attic genetics below "}, {"，下放二楼", "; sent to second floor"},
        {"顶楼新生名额最多", "Attic newborn limit: "}, {"只，下放二楼", "; sent to second floor"},
        {"二楼遗传低于", "Second-floor genetics below "}, {"，下放一楼左", "; sent to first-floor left"},
        {"二楼新生名额每房最多", "Second-floor newborn limit per room: "},
        {"只，下放一楼左", "; sent to first-floor left"},
        {"二楼新生交换和平衡分配", "Newborns exchanged and balanced between second-floor rooms"},
        {"一楼左遗传低于", "First-floor left genetics below "}, {"，转备战", "; sent to combat"},
        {"带职业成年亲本不转战备，进入淘汰复查", "Classed adult parent goes to removal review instead of combat"},
        {"备战真实总和 ", "Combat real-stat total "}, {"（下限", " (minimum "},
        {"），真实≤", "), real stats ≤"}, {"属性 ", " count "}, {" 项", " stats"},
        {"猫咪、房间或日期已变化，请重新生成筛选方案后确认", "Cat, room or day changed. Regenerate and confirm the screening plan."},
        {"此猫不在家园，无法移动", "This cat is not at home and cannot be moved"},
        {"当前位置", "Current location"}, {"移动功能暂不可用", "Move function is temporarily unavailable"},
        {"家园或猫咪的位置已经变化，请重新选择", "House or cat location changed. Choose again."},
        {"已移至 ", "Moved to "}, {"移动未完成，请重新选择", "Move incomplete. Choose again."},
        {"移动中断，已停止本次操作", "Move interrupted; current action stopped"},
        {"家园场景已经变化，移动已取消", "House scene changed; move cancelled"},
        {"场景或猫咪已变化，操作已取消", "Scene or cat changed; action cancelled"},
        {"投送等待已停止，请在原生界面确认当前状态", "Delivery wait stopped. Check the native UI."},
        {"本次操作中断，未自动重试", "Action interrupted; not retried automatically"},
        {"投送操作已交由原生界面处理", "Delivery has been handed to the native UI"},
        {"场景已变化，后续操作已取消", "Scene changed; remaining actions cancelled"},
        {"比尼斯博士", "Dr. Beanies"}, {"布奇", "Butch"}, {"汀可", "Tink"},
        {"弗兰克", "Frank"}, {"杰克宝宝", "Baby Jack"}, {"特蕾茜", "Tracy"},
        {"风琴师", "Organ Grinder"}, {"史蒂文", "Steven"},
        {"猫咪或家园界面暂不可用", "Cat or house UI is unavailable"},
        {"尚未解锁", "Not unlocked"}, {"此角色不接收猫咪", "This NPC does not accept cats"},
        {"当前不接收此猫（条件或接收状态不符）", "This cat is not currently accepted (requirements or state)"},
        {"猫咪正在其他交互中", "Cat is busy with another interaction"},
        {"投送管道正在使用中", "Delivery pipe is busy"},
        {"等待投送管道复位", "Waiting for delivery pipe reset"},
        {"等待投送界面收起", "Waiting for delivery UI to close"},
        {"请先关闭当前原生面板", "Close the current native panel first"},
        {"已遗弃", "Discarded"}, {"已送至 ", "Sent to "},
        {"投送状态已变化，请查看原生界面", "Delivery state changed. Check the native UI."},
        {"猫咪已离开投送管道，后续操作已取消", "Cat left the delivery pipe; remaining actions cancelled"},
        {"NPC 面板已关闭，后续操作已取消", "NPC panel closed; remaining actions cancelled"},
        {"正在遗弃…", "Discarding..."}, {"正在送至 ", "Sending to "},
        {"原生投送中断，未自动重试", "Native delivery interrupted; not retried automatically"},
        {"新生打标失败或年龄已变化", "Newborn marking failed or age changed"},
        {"已按出生房间打标", "Marked by birth room"},
        {"猫咪界面暂未打开，请重试", "Cat details did not open. Retry."},
        {"已打开猫咪界面", "Cat details opened"},
        {"未能进入投送管道，未自动重试", "Could not enter delivery pipe; not retried automatically"},
        {"位置数据已经变化", "Location data changed"},
        {"箱子暂不可用", "Box is unavailable"}, {"箱子已满", "Box is full"},
        {"此猫当前不能进入箱子", "This cat cannot enter the box now"},
        {"无法读取房间位置", "Cannot read room positions"},
        {"移动未完成，请刷新后重试", "Move incomplete. Refresh and retry."},
        {"；剩余操作未执行", "; remaining actions were not run"},
        {" 的目标房间或箱子目前不可用", " has an unavailable target room or box"},
        {"原投送去向目前不可用", "Original delivery destination is unavailable"},
        {"；已保留原选择，请等待或修改后再确认", "; original choice kept. Wait or change it before confirming."},
        {"已确认，开始处理", "Confirmed; processing started"},
        {"无需调整", "No changes needed"}, {"当前操作结束后停止", "Stop after the current action"},
        {"已停止处理", "Processing stopped"},
        {"家园或日期已变化，已停止处理", "House or day changed; processing stopped"},
        {"等待返回家园后继续", "Waiting to return home"},
        {"家园数据暂不可用", "House data is unavailable"},
        {"等待房间舒适度数据稳定", "Waiting for room comfort data to stabilize"},
        {"房间舒适度数据未就绪", "Room comfort data is not ready"},
        {"当前操作等待超时，请查看原生界面", "Current action timed out. Check the native UI."},
        {"老猫数量控制处理完成", "Adult population control completed"},
        {"新生猫筛选处理完成", "Newborn screening completed"},
        {"执行期间猫咪资料、位置或家具被改变，已停止处理", "Cat data, location or furniture changed during execution; processing stopped"},
        {"待处理猫咪已不可用", "Cat to process is unavailable"},
        {"投送管道或界面尚未复位，请查看游戏界面", "Delivery pipe or UI has not reset. Check the game."},
        {"投送去向不可用", "Delivery destination is unavailable"},
        {" 的操作当前不可执行", " cannot be processed right now"},
        {"正在处理 ", "Processing "},
    };
    const auto found = english.find(chinese);
    return found == english.end() ? chinese : found->second;
}
inline const char* NpcLabel(int id) {
    static constexpr const char* names[] = {"比尼斯博士", "布奇", "汀可", "弗兰克", "杰克宝宝", "特蕾茜", "风琴师", "史蒂文"};
    return id >= 0 && id < 8 ? Tx(names[id]) : "";
}
}
